### ISSUE TITLE
eslint can not handle react 16 fragment syntax

### ISSUE THREAD

**Issue by EECOLOR** [kaliberjs/build#103]
Just try it:
```jsx
<>
  <div />
  <div />
</>
```

Warns about `quotes`

**Comment by EECOLOR** [comment]
Hmm, https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html states that jsx support for fragment syntax will only be available for babel 7 which is currently still in beta.

**Comment by EECOLOR** [comment]
In order to make `<React.Fragment>` work we need to add the following to `.eslint`:

```
"react/jsx-no-undef": ["warn", { "allowGlobals": true }]
```

**Comment by EECOLOR** [comment]
https://github.com/eslint/eslint/issues/9662

**Comment by EECOLOR** [comment]
Once babel 7 comes out we can use this: http://babeljs.io/docs/en/next/v7-migration

**Comment by klaasman** [comment]
https://babeljs.io/blog/2018/08/27/7.0.0

**Comment by EECOLOR** [comment]
Don't think this is an issue anymore
