### ISSUE TITLE
`*.html.js` not re-rendered with updated css hash after saving an `*.entry.css`

### ISSUE THREAD

**Issue by klaasman** [kaliberjs/build#118]
To reproduce:

1. apply patch:

```diff
diff --git a/example/src/index.html.js b/example/src/index.html.js
index abd568d..31d24e1 100644
--- a/example/src/index.html.js
+++ b/example/src/index.html.js
@@ -10,6 +10,7 @@ import firebase from 'firebase-admin'
 import bg1 from './bg1.jpg'
 import SharedComponent from '/partials/SharedComponent?universal'
 import '/partials/NotRendered?universal'
+import '/test.entry.css'
 
 main.routes = {
   match: ({ pathname }, request) => pathname === '/'
diff --git a/example/src/test.entry.css b/example/src/test.entry.css
new file mode 100644
index 0000000..90439ba
--- /dev/null
+++ b/example/src/test.entry.css
@@ -0,0 +1,3 @@
+body {
+  background-color: hotpink;
+}
```

2. run example
2. change the background-color
3. see the example hot-reload
4. hard-refresh the example
5. see the previous background-color (due to simply loading the previous css-hash which is hardcoded in the html)

**Comment by EECOLOR** [comment]
This will be a tricky one. The 'template' (a webpack term) is not re-rendered because the hash is unchanged. It turns out to be the hash of the compilation, so it will be quite tricky to figure this one out.

**Comment by EECOLOR** [comment]
https://github.com/kaliberjs/build/issues/71
