### ISSUE TITLE
CSS in JS

### ISSUE THREAD

**Issue by EECOLOR** [kaliberjs/build#127]
I think we want to support this and maybe favor a particular style (or develop our own version).

I don't think it should replace the current CSS mechanism as it still has value. 

This presentation has some interesting overviews: https://www.youtube.com/watch?v=19gqsBc_Cx0
The slides (seems to missing some): https://speakerdeck.com/mxstbr/styling-intro

What is missing in most discussions about CSS in JS is the lack of source maps.

I like the styled component approach ``div`color: hotpink;` `` for a few reasons:
- It is not in jsx and there is no need to deal with its interpolation
- Modularization (unique classnames) can be done without writing the link yourself
- Dynamic stuff becomes easy ``x => div`color: ${x.color};` `` or ``div`color: ${x => x.color};` ``
- It helps reusing styles and build a style component library for your application

**Comment by EECOLOR** [comment]
https://github.com/styled-components/comparison

**Comment by EECOLOR** [comment]
A few other resources:
https://github.com/MicheleBertoli/css-in-js
https://emotion.sh/
https://glamorous.rocks/
https://www.npmjs.com/package/styled-jsx
https://www.reddit.com/r/reactjs/comments/84m529/styled_components_or_glamarous_or_emotion/
https://github.com/markerikson/react-redux-links/blob/master/react-styling.md

It's easy to get lost, but I think we have to keep reminding ourselves what we want to achieve here. Maybe creating a list of use-cases would help

**Comment by klaaz0r** [comment]
Having done some work with styled-components I would consider avoiding the strings for CSS, a simple button doesn't create a problem. Having a button with themes, media queries etc. becomes something like this: https://github.com/xDae/styled-bootstrap/blob/master/src/Button/Button.js both emotion and styled have options for object syntax instead of strings

**Comment by EECOLOR** [comment]
@klaaz0r What would that example look like with object syntax?

Maybe it is sufficient to show a few examples where we can see the string version and object version. These examples should showcase what the object version makes better.

**Comment by klaaz0r** [comment]
Styled-components look something like this: 

```js 
const Input = styled.input.attrs({
  type: 'text',
  size: props => props.small ? 3 : 8
})
```
However the way emotion does it seems a bit cleaner (it had the feature from the start unlike styled) 

```js
const Link = styled.a(props => ({
  minWidth: '12rem',
  margin: '0 auto 20px',
  padding: props.primary ? 18 : 16,
  borderRadius: 5,
  textDecoration: 'none',
  border: props.primary
    ? 'none'
    : '3px solid currentColor',
  background:
    props.primary &&
    'linear-gradient(90deg, #D26AC2, #46C9E5)',
  color: props.primary ? '#1D2029' : '#D26AC2',
  '&:hover': {
    opacity: '0.95'
  },
  '@media (min-width: 768px)': {
    margin: '0 20px 0 0',
    '&:last-child': {
      margin: 0
    }
  }
}))
```

**Comment by EECOLOR** [comment]
I wrote this down for comparison:
```js
const Link = props => styled.a`
  min-width: 12rem;
  margin: 0 auto 20px;
  padding: ${ props.primary ? `18` : `16` };
  border-radius: 5;
  text-decoration: none;
  border: ${ props.primary
    ? `none`
    : `3px solid currentColor` };
  background: 
    ${ props.primary &&
    `linear-gradient(90deg, #D26AC2, #46C9E5)` };
  color: ${ props.primary ? `#1D2029` : `#D26AC2` };
  &:hover: {
    opacity: 0.95;
  }
  @media (min-width: 768px): {
    margin: 0 20px 0 0;
    &:last-child: {
      margin: 0;
    }
  }
`
```
I am still not sure if one style is better than the other. Can you point out why you have a preference for the object style?

**Comment by klaaz0r** [comment]
@EECOLOR because once something is a string it's hard to go back you don't want to start parsing the styles. If we keep everything as an object you can do more things like applying enhancers, writing your own CSS middleware etc. And of course beautifying code is way easier

**Comment by EECOLOR** [comment]
This might also be an interesting option:
https://blog.callstack.io/announcing-linaria-1-0-d5c7756ff511
https://github.com/callstack/linaria

**Comment by klaasman** [comment]
here's another one: https://github.com/4Catalyzer/astroturf

**Comment by klaasman** [comment]
It might be interesting to follow this issue: https://github.com/facebook/create-react-app/issues/5224

**Comment by EECOLOR** [comment]
Do you know how editor support is for CSS in js files?

**Comment by EECOLOR** [comment]
We are currently working on more strict CSS rules (see `style-lint` branch). This means that, even if editor support is now great, we will not implement this until we have stabilized our CSS policies.

When the policies have stabilized, if we would want to add support for CSS in JS, we would need to investigate support from our linter plugins. They would probably be more complicated.
