### ISSUE TITLE
Fix cross-origin errors cdn polyfill (for rollbar)

### ISSUE THREAD

**Issue by daveykropf** [kaliberjs/build#130]
To fix the following message in rollbar, we need to add the `crossOrigin='true'` attribute in the polyfill script tag.

```javascript
(unknown): Script error.
1
File "(unknown)" line (unknown) col 0 in [anonymous]
```

So instead of:
```html
<script defer src='https://cdn.polyfill.io/v2/polyfill.min.js?features=default,es2015,es2016,es2017' />
```

We have to use:
```html
<script defer crossOrigin='true' src='https://cdn.polyfill.io/v2/polyfill.min.js?features=default,es2015,es2016,es2017' />
```

Documentation:
* [Rollbar - Unknown(Script Error)](https://docs.rollbar.com/docs/unknown-script-error)
* [React - Cross-origin Errors](https://reactjs.org/docs/cross-origin-errors.html)

**Comment by EECOLOR** [comment]
It should be `crossOrigin='anonymous'`, but would be a nice addition for the template

**Comment by EECOLOR** [comment]
We probably should include `es2018` as well

**Comment by klaasman** [comment]
`es2018` doesn't seem to be a thing: https://github.com/Financial-Times/polyfill-service/search?q=es2018&unscoped_q=es2018

**Comment by EECOLOR** [comment]
https://github.com/Financial-Times/polyfill-service/pull/1779

**Comment by EECOLOR** [comment]
Financial-Times/polyfill-service#1779 is solved

**Comment by EECOLOR** [comment]
https://github.com/kaliberjs/build/commit/81e4be742780494004116dba6113f75a078eeb07
