### ISSUE TITLE
Hardening for serve

### ISSUE THREAD

**Issue by EECOLOR** [kaliberjs/build#131]
We might want to consider setting the following headers:

```
Header append X-Frame-Options SAMEORIGIN
Header set X-Content-Type-Options nosniff
Header set X-XSS-Protection "1; mode=block”
```

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection

If not in the `serve`, we could add it in the template.

Note that this might be a part of helmet already.

**Comment by klaasman** [comment]
It looks like those headers are set with the [default helmet](https://helmetjs.github.io/docs/) configuration:
- [`X-Frame-Options: SAMEORIGIN`](https://helmetjs.github.io/docs/frameguard/)
- [`X-Content-Type-Options: nosniff`](https://helmetjs.github.io/docs/dont-sniff-mimetype/)
- [`X-XSS-Protection: 1; mode=block`](https://helmetjs.github.io/docs/xss-filter/)
