### ISSUE TITLE
An empty/missing README.md in the library directory results in an empty detail page on npmjs.org

### ISSUE THREAD

**Issue by klaasman** [kaliberjs/build#143]
https://www.npmjs.com/package/@kaliber/build

![image](https://user-images.githubusercontent.com/85814/43582642-5ca8541e-965d-11e8-9e4d-07367129be0d.png)

**Comment by klaaz0r** [comment]
Fixed with version 0.0.68 https://www.npmjs.com/package/@kaliber/build
We do however need to invest some time in enhancing the docs
