### ISSUE TITLE
PNG compression - larger filesize

### ISSUE THREAD

**Issue by coffeemedia** [kaliberjs/build#150]
Compressing .png files can result in larger file sizes.

Input file: koffie.png
Filesize: 419215

Compressing koffie.png with https://tinypng.com/ results in
Output file: koffie-406999.png
Filesize: 406999

Compressing koffie.png with @kaliber/build results in
Output file: 9f12334ec3cbb380112d3ef680cf3913.png
Filesize: 1074518

![9f12334ec3cbb380112d3ef680cf3913](https://user-images.githubusercontent.com/1494115/44468827-65b30800-a626-11e8-9e9e-bea46d9d10c4.png)
![koffie-406999](https://user-images.githubusercontent.com/1494115/44468828-65b30800-a626-11e8-8b50-96dab9d78842.png)
![koffie](https://user-images.githubusercontent.com/1494115/44468829-664b9e80-a626-11e8-8e14-ecb5446683e5.png)

**Comment by EECOLOR** [comment]
https://github.com/gruntjs/grunt-contrib-imagemin/issues/118

No indication yet what causes it though. I guess I need to go look at the default settings and compare them with the advised settings.

**Comment by EECOLOR** [comment]
@coffeemedia Was this during a watch or during a build (`NODE_ENV=production`)?

**Comment by coffeemedia** [comment]
@EECOLOR During a watch on local development environment.

**Comment by EECOLOR** [comment]
@coffeemedia Do you have this problem with a build (`NODE_ENV=production`) as well?

**Comment by coffeemedia** [comment]
Closed due to inactivity
