### ISSUE TITLE
The custom eslint resolver marks images loaded with the maxsize loader as false duplicates

### ISSUE THREAD

**Issue by klaasman** [kaliberjs/build#154]
![image](https://user-images.githubusercontent.com/85814/47570791-4cd11680-d937-11e8-9d06-efbe84b6baec.png)

**Comment by EECOLOR** [comment]
I don't think this is possible to solve

**Comment by EECOLOR** [comment]
Note to self: check if this is still the case when you release `style-lint`

**Comment by EECOLOR** [comment]
Will be solved once `style-lint` is released

**Comment by EECOLOR** [comment]
https://github.com/kaliberjs/build/commit/eaf23253dda631cf4c92ec33db0feee8bec8b52e
