### ISSUE TITLE
What would be the workflow when used in a wordpress plugin?

### ISSUE THREAD

**Issue by larsvankleef** [kaliberjs/build#166]
It would be nice if there was a workflow example in the docs for using kaliberjs inside of a wordpress plugin. 

Some plugins render special components inside of the wp-admin or in on the front end of the wordpress site. These components use for example react to generate a graph view of the data found in wordpress.

Structure folder of the most plugins:
- src
  - javascripts
  - stylesheets
- dist
  -(@kaliberjs/build)

**Comment by EECOLOR** [comment]
@larsvankleef What did you end up using?

**Comment by larsvankleef** [comment]
This question came out of the idea that you would deliver a plugin that would carry his own css and javascript inside the plugin folder. Like yoast seo and other bigger plugins in wordpress are working.

When working on this plugin we came to the conclusion that is wasn’t a good idea to pack the css and javascript assets inside the plugin folder. Because the javascript and css would be domain specific and could not be reusable in other scenarios.

The plugin packs some domain agnostic assets (admin assets) but these are now placed inside the project where the plugin is used. Because this plugin is not used somewhere else then in this project we made the decision to not separate these form the main project. 

We end up building an api and document the end points. The assets for this plugin are placed inside a separate folder in side the `src` folder. The assets could be separated from the project if there is a need to but we did not find this necessary for now. 

So we did not really 'used' something but we just placed the files inside a separate folder.

**Comment by EECOLOR** [comment]
Ahh right, well if we wanted to create a plugin in the future that lives in a separate repository, we could use @kaliber/build as the build system.

This would mean we would need to setup a CI job that performed the build and create a package containing the appropriate files and publish it to the correct repo. Here we could go two ways:

- Create a single composer package that contains both php and assets
- Create separate packages, composer and npm

It depends on the specific use-case to determine what would be the best approach. There is also a scenario where we could tell @kaliber/build to include certain files in the build. This can be done in serveral ways:

- Create a synlink from the `src` directory
- Create entry files (css and js) and import the plugin files from those files
- Import the files (css and js) from some entry in the `src` directory

Anyway, plenty of opportunities
