### ISSUE TITLE
*.raw.* import throws an error since v84

### ISSUE THREAD

**Issue by peeke** [kaliberjs/build#171]
When you import a raw file (given the *.raw.* file format) from a universal React file, this throws an error: 

```
Uncaught ReferenceError: __webpack_exports__ is not defined
```

Checking different versions, this seems to have been introduced in version 85. In the example project of this repo, the import actually seems to work (still throwing the error). But in other projects it breaks the JS bundle, causing the component not to be rendered.

**Comment by EECOLOR** [comment]
@peeke Have you tried the latest version (remove the local `yarn.lock` and `node_modules` directory)?

I will probably need to investigate. It could be a tricky problem.

**Comment by EECOLOR** [comment]
Hmm, it seems I can't reproduce it. This problem might be caused by a module that is not up-to-date.

**Comment by peeke** [comment]
I think my initial description wasn't super clear: I'm talking about a client-side error, it shows in the browser console.

Steps to reproduce are:
 - Make a duplicate of `/example/src/red.svg`, rename it to `/example/src/red.raw.svg`
 - In `/example/src/partials/Test.js`, import it. This will throw the error. 

The error only seems to occur when the import happens in a JavaScript module that is (or has a parent) imported with the `?universal` flag.
