### ISSUE TITLE
Sourcemaps: 'sources' -> root is not correct after building within example Jekins

### ISSUE THREAD

**Issue by larsvankleef** [kaliberjs/build#183]
This path is put into the sources section of the Sourcemaps this should be a relative path.

```
/var/lib/jenkins/workspace/{project}/node_modules/react-dom/cjs/
```

This could be a problem with a default changing in `babel-loader` or `@babel/core`

**Comment by EECOLOR** [comment]
Solved in the latest release, now uses relative paths.

**Comment by EECOLOR** [comment]
https://github.com/kaliberjs/build/commit/0b5ca31ad6077c7dade0e9fce67c8376d358c5cb
