### ISSUE TITLE
TypeError: createValueParser is not a function

### ISSUE THREAD

**Issue by peeke** [kaliberjs/build#188]
TypeError: createValueParser is not a function 
at ... 
at parseValue (/node_modules/@kaliber/build/stylelint-plugins/machinery/ast.js:61:37) 
at isIntrinsicValue (/node_modules/@kaliber/build/stylelint-plugins/rules/layout-related-properties/index.js:111:20) 
at decls.forEach.decl (/node_modules/@kaliber/build/stylelint-plugins/rules/layout-related-properties/index.js:82:48) 
at Array.forEach (<anonymous>) at rule (/node_modules/@kaliber/build/stylelint-plugins/rules/layout-related-properties/index.js:81:11) 
at root.walkRules.rule 
...

Couldn't figure out what exactly is causing this error.

**Comment by EECOLOR** [comment]
When do you get this error?

If it is in Visual Studio Code, which plugin are you using for Stylelint?

**Comment by peeke** [comment]
Yes, it's a VS Code error indeed:
![image](https://user-images.githubusercontent.com/4712314/77620220-28b5a280-6f3a-11ea-9fb8-016eab8a8769.png)

It's definitely related to the intrinsic size rule, but I cannot seem to reproduce outside of this project: https://github.com/Kaliber/kaliber-academie-Melissa_Bos

The project is still on build version 102, locally I tried upgrading to 104 which did not seem to make a difference.

The problem occurs when violating the rule:
```
.icon {
  height: 10px;
}
```
But also when conforming to it:
```
.component {
  min-height: 100vh !important;
}
```

Stylelint extension is `stylelint-stzhang`

**Comment by EECOLOR** [comment]
Yes, I missed this during the last update.

A few changes are required:
- The `postcss-values-parser` now returns an object containing `parse`
- The response from that function seems to omit a level `result.first` becomes `result`
- Type `number` has become `numeric`
- Possibly some other changes

It's relatively easy to fix, not sure if I get around to it though. For the specific project you can edit the relevant `@kaliber/build` files inline if this hinders you too much. Another option is to disable the `isIntrinsicValue` check `layout-related-properties` (by uncommenting that line), it seems that is the only part that uses the function.
