### ISSUE TITLE
SSR with php

### ISSUE THREAD

**Issue by larsvankleef** [kaliberjs/build#199]
I know this is a weird and probably not that stable solution but i found it fun to get it working. A few days ago I found this package that looks simple and stable enough to give it a try. But it requires the server side code to be generated and be available as a file. But i can not figure out how to force the buildtool to generate these files next to the client side code and save it in a folder.

What i would like to accomplish is having the following structure work 
‘src/includes/components/dropdown/dropdown.ssr.js’

Will result into 
- `kaliberjs/includes/components/dropdown/dropdown.php`
- `kaliberjs/includes/components/dropdown/dropdown-client.js`
- `kaliberjs/includes/components/dropdown/dropdown-server.js`

```dropdown.php
// dropdown.php
use Spatie\Ssr\Renderer;
use Spatie\Ssr\Engines\V8;

$engine = new V8();

$renderer = new Renderer($engine);

echo $renderer
    ->entry('${pathToGeneratedServerFile}')
    ->render();
```

```dropdown-server.js
// dropdown-server.js

/* global context, dispatch */

import Dropdown from './dropdown';
import React from 'react';
import ReactDOMServer from 'react-dom/server';

const html = ReactDOMServer.renderToString(
   <App />
);

dispatch(html)
```
https://github.com/spatie/server-side-rendering
https://github.com/spatie/laravel-server-side-rendering

**Comment by EECOLOR** [comment]
Basically having something with the `*.html.js` extention does most of the work. See https://kaliberjs.github.io/build/how-to/server-side-rendering/

> the library performs the following tasks:
> - picks up the {name}.html.js file
> - detects it is a function
> - grabs the registered html renderer and prepares it with the file
> - emits a {name}.html.js file that essentially contains a function like this: `props => render(template(props))`

This means you can `require` the file and execute the resulting function.

So the resulting file should look like this:

```js
const renderer = require('./...')
const props = context
dispatch(renderer(props))
```

So, if you create a single `entry` file (https://kaliberjs.github.io/build/conventions/#*.entry.js):

```js
const { component, props } = context
const renderer = require(`./${component}.html.js`)
dispatch(renderer(props))
```

You could call it like this from php:
```php
use Spatie\Ssr\Renderer;
use Spatie\Ssr\Engines\V8;

$engine = new V8(); // Or Node

$renderer = new Renderer($engine);

echo $renderer
    ->context('component', 'myComponent/Something')
    ->context('props', ['user' => 'Bert', 'friend' => 'Ernie'])
    ->entry('${hashOfEntryFromChunkManifest}')
    ->render();
```

**Comment by EECOLOR** [comment]
Note that the component `*.html.js` should internally import the actual component using `?universal` if you want it to also be rendered on the client.

For clarity you can offcourse register the `html` renderer with another name, this allows you to do the same with `*.ssr.js` (see https://kaliberjs.github.io/build/template-renderers/)

**Comment by larsvankleef** [comment]
Thanks for suggestions it helpt a lot with getting the files where thy needed to go.

I got it working after 1 hour of struggling with it. It can now render the serverside html code and load the required files to get the universal part working.

**Comment by EECOLOR** [comment]
Could you share the code you used?

**Comment by larsvankleef** [comment]
This is the code i used to get it working in a modded wordpress envoirment that works with the kaliberjs/build tool.

## Get the package form composer
`composer require spatie/server-side-rendering`

## Some helper functions and config.

```diff
// config/default.js
-      php: '/php-renderer'
+     php: '/php-renderer',
+     ssr: '/ssr-renderer'
```

```js
// src/ssr-renderer.js -> based of the default *.html.js renderer

const ReactDOMServer = require('react-dom/server')
const { isElement } = require('react-dom/test-utils')

module.exports = function htmlReactRenderer(template) {
  if (!isElement(template)) return template
  return ReactDOMServer.renderToStaticMarkup(template)
}
```

```js
// src/ssr-entry.js -> this file is used to load the component form the file system.
/* global context, dispatch */
const path = require('path')

const { component, props } = context
const systemPath = path.join(path.dirname(__dirname), 'www', 'kaliberjs', 'includes', component)

const renderer = require(path.join(systemPath, `${component}.ssr.js`))
dispatch(renderer(props))
```

```php
<?php
// include-ssr.php

use Spatie\Ssr\Renderer;
use Spatie\Ssr\Engines\Node;

function _include_ssr($component, $props) {
  $engine = new Node($GLOBALS['NODE_PATH'], $GLOBALS['NODE_TEMP']);
  $renderer = new Renderer($engine);
  
  // load the scripts to get universal working
  kaliber_renderEntry(sprintf('includes/%s/%s.ssr.js', $component, $component)); 

  // load the component and render it into the page
  echo $renderer
    ->entry(sprintf('%s/kaliberjs/ssr-entry.js', $_SERVER['DOCUMENT_ROOT']))
    ->debug($GLOBALS['WP_DEBUG'])
    ->context('component', $component)
    ->context('props', $props)
    ->render();
}
```

## Example using the utils
The file has a *.ssr.js extension to make sure the code is loaded with the correct loader.

```js
// src/includes/ssr-example/ssr-example.ssr.js
import SsrExampleApp from './ssrExampleApp.js?universal'

export default function ssrExample({ user, friend }) {
  return (
    <div>
      props from php <pre>{JSON.stringify({ user, friend })}</pre>
      <SsrExampleApp />
    </div>
  )
}
```

### ssrExampleApp.js
```js
//  src/includes/ssr-example/ssrExampleApp.js
export default function ssrExampleApp() {
  const [isOpen, setIsopen] = React.useState(false)
  const [time, setTime] = React.useState('ssr')

  React.useEffect(() => {
    const timeout = setTimeout(() => {
      setTime(new Date())
      setIsopen(true)
    }, 1000)

    return () => clearTimeout(timeout)
  }, [])

  return (
    <div>
      <i>universal</i>

      <p>{JSON.stringify(time)}</p>

      <button onClick={handleClick}>open</button>
      {isOpen && <div>this content is hidden</div>}
    </div>
  )

  function handleClick () {
    setIsopen((current) => !current)
  }
}
```

### Include the component into your html and add some props.
```php
<?php include_ssr('ssr-example', ['user' => 'Bert', 'friend' => 'Ernie']); ?>
```

**Comment by larsvankleef** [comment]
As spatie says in their readme.

"As a final disclaimer, judging by the amount—well, lack—of people blogging about rendering JavaScript applications in PHP, this whole setup is uncharted territory. There may be more unknown caveats lurking around the corner."

I did not test this concept with more complex components. But it works fine with the component given above. You can see the html change when the js kicks in. From that point you can interact with the button and hide or show the content.

**Comment by EECOLOR** [comment]
Thank you for sharing this!

You can simplify / improve a few things I think:

- Instead of using an absolute path in `require` you could use a relative path. 
- Instead of copy-pasting the code from the `html-renderer` you could point to the `html-renderer` from you configuration

In any case, thanks for doing the research on this!
