### ISSUE TITLE
Minify javascript

### ISSUE THREAD

**Issue by EECOLOR** [kaliberjs/build#2]
https://github.com/babel/babili/issues/509

**Comment by EECOLOR** [comment]
We could try Uglify to see if that works, it will however probably give other problems.

**Comment by klaasman** [comment]
We'll need this for our first production-release.

**Comment by EECOLOR** [comment]
Hmmm: https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/47

**Comment by EECOLOR** [comment]
https://github.com/Rich-Harris/butternut

> Warning: this is alpha software. Test thoroughly before using in production!

**Comment by EECOLOR** [comment]
And closure compiler seems a bit much for what we need.

**Comment by EECOLOR** [comment]
Maybe we should stick with just gzip for the time being until we have a premade solution that works
