### ISSUE TITLE
Stylelint message is incorrect

### ISSUE THREAD

**Issue by melissabos18** [kaliberjs/build#206]
When nesting into the hover statement the stylelint gives an incorrect message on the `display` property.
An example:

```
.Parent {
  position: relative;

  & > .Child {
    display: none;
  }

  &:hover {
    & > .Child {
      display: inline-block;
    }
  }
}
```

The stylelint gives an message on the `display: inline-block`, it says: illegal non-layout related prop
`display` can only be used by root rules - move to another root rule. 

But the thing is that the display property has to change when the user is hovering over the parent element. The default is `display: none`, when hovering over the parent the `display` has to change to `inline-block`. 

So i think folles the rules by this one, https://github.com/kaliberjs/build/tree/master/library/stylelint-plugins/rules/naming-policy#state. There is no need of an stylelint message.

**Comment by EECOLOR** [comment]
According to the rules it should work like this:

```css
.Parent {
  position: relative;

  & > .ParentChild {
    display: none;
  }

  &:hover {
    & > .ParentChild {
      display: inline-block;
    }
  }
}
```

Note that I renamed `Child` to `ParentChild` (following the documentation you linked).

**Comment by melissabos18** [comment]
Ah yes it works fine like that, using the parent className also for the child. But maybe it is better to put it in the stylelint message?

**Comment by EECOLOR** [comment]
It would be nice, but it's quite tricky. The error you are receiving is one that warns about layout v.s. non-layout related properties. The mechanism of 'state' only disables that other rule. There is no easy way to determine from the code that you are actually trying to use the 'state' mechanism. It could very well be that you are not trying to do that.
