### ISSUE TITLE
Enforce color variable naming convention through linting rule

### ISSUE THREAD

**Issue by peeke** [kaliberjs/build#210]
In one of our development meetings, we have decided to use the same color variable naming system as the material design system uses:

`--color-name-xxx` where xxx is a number between 0 and 900, 0 being very light, 900 very dark. 

It would be nice if we can enforce this convention through a linting rule

**Comment by EECOLOR** [comment]
Why did you close it?

**Comment by peeke** [comment]
I think we need to have a discussion about this first, because Martijn had a usecase to not use numbering. Wanted to prevent us from prematurely implementing this in the meantime.
