### ISSUE TITLE
@supports @media order matters in production build

### ISSUE THREAD

**Issue by peeke** [kaliberjs/build#211]
Locally, it doesn't matter wether you nest @supports inside @media, or the other way around. When building a production build however, if you nest @supports within @media, the rules get dropped:

```css
@media (--viewport-lg) {
  @supports(display: grid) {
    /* These rules get dropped */
  }
}
```

```css
@supports(display: grid) {
  @media (--viewport-lg) {
    /* These rules do not get dropped */
  }
}
```

Regardless of which pattern is preferred, the behavior should change when building a production build.

**Comment by EECOLOR** [comment]
The behavior should indeed not change. This requires some investigation.

**Comment by peeke** [comment]
Not sure when this changed, but this behaviour doesn't seem to be present anymore (version `v0.0.112`)
