### ISSUE TITLE
Changes in cssGlobal files do not update your css bundles

### ISSUE THREAD

**Issue by peeke** [kaliberjs/build#220]
Whenever you make changes to the files in the folder `/cssGlobal`, these changes are not included in the generated bundle. Change to files in the folder `/cssGlobal` _do_ trigger some changes (you can see the build terminal respond), but to get your changes in the generated bundle you have to save a css file outside of the `/cssGlobal` folder to trigger the build to include your changes in the final bundle.

**Comment by EECOLOR** [comment]
This needs some further investigation. A build is correctly triggered and the variables are picked up by the postcss-custom-properties plugin. We'll have to dive into that plugin to find out what is causing these issues.
