### ISSUE TITLE
Cache-busting of files like `index.css`

### ISSUE THREAD

**Issue by klaasman** [kaliberjs/build#28]
It would be useful for cache-busting to have a unique id in the filenames of files like `index.css` and `index.js` - traditional webpack apps often contain a hash in the filename, something like this would be a good solution.

**Comment by EECOLOR** [comment]
I know what you mean, but that would require us to pass in the names to the templates, complicating things a bit.

It is theoretically possible, but maybe a simpeler solution is better. You could for instance just add `?v=${Date.now()}` in your template (only a solution for static sites).

Also, do we really need cache-busting? Wouldn't the correct combination of headers fix stuff based on the file itself; if it changed it is fetched again.

I have no preferred approach, just some thought. Let me know what you think.

**Comment by klaasman** [comment]
I can't remember a project from the past where we've setup cache-headers (with etags, etc) correctly, there was always some moment where someone had to perform hard-reloads because new assets weren't served.

In my experience the best cache-busting is a combination of cache-headers + unique filenames.

**Comment by EECOLOR** [comment]
We could add a plugin like the [ExtendedAPIPlugin](https://github.com/webpack/webpack/blob/master/lib/ExtendedAPIPlugin.js) that replaces the `__webpack_chunk_hash__` into the `chunk.hash`.

Then we change the `merge-css-plugin` to use `{chunk.name}.css` as output file and in our code we use: 
```js
<link href={`/${__webpack_chunk_hash__}.css`} rel='stylesheet' type='text/css' />
```

Hmm, while writing this I see some problems with this method. We need to think about it some more.
