### ISSUE TITLE
webpack module type `Stylesheet`

### ISSUE THREAD

**Issue by klaasman** [kaliberjs/build#31]
https://medium.com/faceyspacey/webpacks-import-will-soon-fetch-js-css-here-s-how-you-do-it-today-4eb5b4929852

Is this something we can use?

**Comment by EECOLOR** [comment]
I don't think it's useful for us. It's part of an ecosystem that takes a different approach to 'universal'. I think we solve a similar problem when we add a solution for #41 in a (in my personal opinion) easier way.
