### ISSUE TITLE
css-import v10.0.0 has no `onImport` method

### ISSUE THREAD

**Issue by klaasman** [kaliberjs/build#35]
This results in CSS not being compiled on save (for static templates at least)

I'll downgrade the dependency, but the codebase still needs some work to refactor the `onImport` to something else.

- [css-import changelog](https://github.com/postcss/postcss-import/blob/master/CHANGELOG.md#1000---2017-05-12)
- [related discussion](https://github.com/postcss/postcss-import/issues/242)

**Comment by klaasman** [comment]
I've added a branch with an example showing it's broken, to reproduce:
> Make changes to `example/src/test/help-it-is-broken.css` and see
it won't result in updated css. Touching the `index.html.js.css` does
work though.

**Comment by klaasman** [comment]
I accidentally published to NPM from this branch (v0.0.24) - therefore published again (v0.0.25) from master to fix this - FYI. (We might need to clean it up?)

**Comment by EECOLOR** [comment]
They apparently made a big change: https://github.com/postcss/postcss-import/issues/242#issuecomment-259782623

Seems we need to use another method to determine dependencies: https://github.com/postcss/postcss-import/issues/242#issuecomment-259730779

(Don't worry about the published version)
