### ISSUE TITLE
Objects are not valid as a React child

### ISSUE THREAD

**Issue by bvandriel** [kaliberjs/build#48]
Uncaught Error: Objects are not valid as a React child (found: object with keys {key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `Slider`.

-----template-----
```
import Slider from 'components/Slider?universal'
import Testimonial from 'components/Testimonial'

        <Slider>
          <Testimonial name='Léon Rust' jobTitle='CEO' image={leonSrc}>
            De TEG bedrijven moeten impact maken. Het gaat om de beleving die wordt ervaren. De TEG bedrijven moeten ervoor zorgen dat iedereen die met hen in aanraking komt altijd met een goed gevoel naar buiten gaat.
          </Testimonial>

          <Testimonial name='Monique Moos' jobTitle='CFO' image={moniqueSrc}>
            Binnen TEG maken we samen de weg van de toekomst. We inspireren en stimuleren elkaar om telkens nieuwe oplossingen te vinden. Het is onze drijfveer om onze bedrijven, opdrachtgevers en specialisten in hun kracht te zetten.
          </Testimonial>
        </Slider>
```

-----Slider.js-----

```
import styles from './Slider.css'
import { any } from 'prop-types'

export default class Slider extends Component {

  static propTypes = {
    children: any
  }

  render () {
    const { children } = this.props

    return (
      <div className={styles.main}>
        {children}
      </div>
    )
  }
}

```

**Comment by EECOLOR** [comment]
The problem here is that the `?universal` part takes all props passed into the original component and serializes them onto the data attribute so they can be passed in to the runtime (or live) version of the component.

I never realized that `children` also is a prop.

The quick-fix or workaround is to make the outer (imported with `?universal`) component one without children. In this example you would need something like this: 

```
import Slider from 'components/Slider'
import Testimonial from 'components/Testimonial'

export default function TestimonialSlider() {
  return (
     <Slider>
        <Testimonial>
            ...
        </Testimonial>
        <Testimonial>
            ...
        </Testimonial>
      </Slider>
  )
}
```
And the import the `TestimonialSlider` using `?universal`.

**Comment by EECOLOR** [comment]
I have looked into this some more. We could theoretically traverse the children and serialize them in the server code (which now simply does `JSON.stringify` on the props). And then on the client traverse that structure and do `React.createElement` to build up the structure again. This however would become a very tricky exercise for functional and class based components (types).

Another idea is to make use of the ability of the [transform-react-jsx](https://babeljs.io/docs/plugins/transform-react-jsx/) to specify a custom `pragma` (see documentation of transform-react-jsx) and serialize at that point.

All in all I do not think it's worth the effort to support passing children from the server to the client. I will add it to the documentation.
