### ISSUE TITLE
CSS @keyframes override each other

### ISSUE THREAD

**Issue by JoostKiens** [kaliberjs/build#51]
All css @keyframes animations are renamed to `a` when running `yarn build`. This means the last one in the stylesheet wins.

**Comment by EECOLOR** [comment]
What does your `build` command execute (see  `package.json`)?

**Comment by EECOLOR** [comment]
Hmm, seems to be in `cssnano`: https://github.com/ben-eb/cssnano/issues/247

**Comment by EECOLOR** [comment]
Hmm, we probably should not run `cssnano` from the loader, but rather from a separate plugin on the end-result (after concatenation). In any case, we could disable that specific feature from cssnano until we have a better solution.

**Comment by EECOLOR** [comment]
Since we use css-modules, we should probably add this one as well: https://github.com/css-modules/postcss-icss-keyframes

**Comment by JoostKiens** [comment]
👍

**Comment by EECOLOR** [comment]
Using `cssnano` on a module level can be safe because we use `css-modules`, that one however should also make all global stuff (like keyframes) unique. And we should definitely use the `cssnano` option:
```
{
  reduceIdents: false
}
```

We might encounter more of these in the future though.

**Comment by EECOLOR** [comment]
Hmm, seems icss (Interoperable CSS) is something else: https://github.com/css-modules/icss

**Comment by klaasman** [comment]
According to [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/custom-ident) the animation-name's custom-ident-value cannot be global CSS values (`unset`, `initial`, and `inherit`), or `none`. Therefore I guess the mentioned issue (https://github.com/ben-eb/cssnano/issues/247) cannot be the actual bug.

**Comment by klaasman** [comment]
However, as @EECOLOR mentioned, the `reduceIdents: false` should fix this particular issue :-)

**Comment by EECOLOR** [comment]
@klaasman The `isSafe` option (for 3) and `default` preset (for 4) set that option.

What did you mean with you comment about the MDN documentation?

ben-eb/cssnano#247 is not a bug, but the feature only works when the whole css file is processed by postcss. For this reason we might want to remove postcss from the loader and move it to a plugin (like with uglify for javascript). This would allow us to enable more aggressive features like `reduceIdents`.

This would however cause trouble if we wanted to have more than one `.css` file on a page.
