### ISSUE TITLE
Flickity, React and fetching json form a api are acting strange.

### ISSUE THREAD

**Issue by larsvankleef** [kaliberjs/build#60]
It would be great if there was a example on how to do this.

**Comment by EECOLOR** [comment]
Most of the stuff related to the problems you will probably encounter is described here: https://facebook.github.io/react/docs/integrating-with-other-libraries.html

The main rule to keep in your head is:
> If you have some code that is directly manipulating the DOM, make sure React never sees it.

In the case of Flickity, once it's attached to a DOM node, it will modify it. To turn it back the way it found your DOM use `destroy`:
> `destroy` will return the element back to its pre-initialized state.

This means you would need to `destroy` on `componentWillUpdate` (before `render`) and create a new instance on `componentDidUpdate` (after `render`).

To make sure you do not 'reset' Flickity too often you will probably need to implement the `shouldComponentUpdate` method.

Another problem is that Flickity assumes a `window` scope is present. This is not present on the server, so you need to make sure that Flickity is initialized in `componentDidMount`:
```js
componentDidMount() {
  import('flickity').then(Flickity => {
    this.Flickity = Flickity
  })
}
```

The styles should be imported in your main template (for example `index.html.js`) like this:
```js
import 'flickity/css/flickity.css'
```

A full example to give you an idea:

`index.html.js`
```js
import 'flickity/css/flickity.css'

...
```

`Carousel.js`
```js
import './Carousel.css'

export default class Carousel extends Component {

  flickity = null
  state = { showCells: false }

  shouldComponentUpdate(_, newState) {
    return this.state.showCells !== newState.showCells
  }

  componentWillUpdate() {
    this.disableFlickity()
  }

  render() {
    return (
      <div>
        <button onClick={() => this.setState({ showCells: !this.state.showCells })}>show /hide</button>
        <div>
          <div className='main-carousel' ref='carousel'>
            { this.state.showCells && ([
              <div className='carousel-cell' key='1'>1</div>,
              <div className='carousel-cell' key='2'>2</div>,
              <div className='carousel-cell' key='3'>3</div>
            ])}
          </div>
        </div>
      </div>
    )
  }

  componentDidUpdate() {
    this.enableFlickity()
  }

  componentDidMount() {
    import('flickity').then(Flickity => {
      this.Flickity = Flickity
      this.enableFlickity()
    })
  }

  componentWillUnmount() {
    this.disableFlickity()
  }

  enableFlickity() {
    if (!this.flickity) this.flickity = new this.Flickity(this.refs.carousel)
  }

  disableFlickity() {
    if (this.flickity) this.flickity.destroy()
    this.flickity = null
  }
}
```

`Carousel.css`:
```css
:global(.carousel-cell) {
  width: 100%; /* full width */
  height: 160px; /* height of carousel */
  margin-right: 10px;
}
```

**Comment by EECOLOR** [comment]
Oh, and you might run into an issue where, when you click the carousel, it will give you an error like this: "Unable to find element with ID". I'm unsure what causes this, it seems to be a React problem.

This guy has the same issue: https://github.com/RakanNimer/react-google-charts/issues/105

For no apparent reason the error went away in my test case...
