### ISSUE TITLE
css hot-reload bug: css-url in served html is not updated on page-reload

### ISSUE THREAD

**Issue by klaasman** [kaliberjs/build#71]
Stylesheets are hot-reloading as expected, however on a page-reload the initial stylesheet is served (without modifications).

**Comment by EECOLOR** [comment]
It will take some more digging. The problem is that webpack is getting the entry chunk (the template) from cache. Somehow it did not realize the chunk or one of it's modules has changed (probably because they didn't, courtesy of the modules).

**Comment by EECOLOR** [comment]
A workaround, that might be good enough for a while would be to place a small piece of code in the `css-loader` (https://github.com/kaliberjs/build/blob/master/library/webpack-loaders/css-loader.js#L61):

```js
      this.emitFile(filename, css, map.toJSON())

      exports.cssHash = require('crypto').createHash('md5').update(css).digest('hex')

      callback(null, exports)
```
