### ISSUE TITLE
Import css variables (theme) in javascript

### ISSUE THREAD

**Issue by klaasman** [kaliberjs/build#73]
In a lot of projects there's a `theme.css` living in the root of the project. This file is imported in a lot of css files which need some variable(s), for example a breakpoint or a color.

It would be useful to have those variables inside the javascript environment too.

Two possible ways I can think of;

1. Make the `theme.css` a convention and introduce a separate loader for the `theme.css`, which exports an objects with the variables.
    ```js
    import theme from 'theme.css'
    ```

2. Export theme-variables with every `*.css` import, e.g.
    ```js
    import styles, { theme } from './ComponentStyles.css'
    ```

**Comment by klaasman** [comment]
Or;

3. the other way around, import js from css
    ```css
     @import 'theme.js'
    ```

One possible frustrating thing could be the fact that variables in css are normally `like-this-cased`, whereas in js we're usually using `camelCase`.

**Comment by klaasman** [comment]
We could of course convert the case to the preferred format per environment.

**Comment by EECOLOR** [comment]
I don't think I will get to rewrite the template plugin anytime soon.

Using a `.css` file to define variables is tricky because that would require us to parse the css and extract the variables. The other way around would be doable: importing a `.js` file in a `.css` file. In order to that we need a loader that loads the `.js` and converts it to valid css content that contains the variables. This loader could be triggered by something like `?asCssVariables`.

`variables.js`
```js
export default {
  variable1: 'red',
  variable2: 'green'
}
```

`some.js`
```js
import variables from 'variables'
...
```

`some.css`
```css
@import 'variables.js?asCssVariables`
...
```

**Comment by klaasman** [comment]
Parsing css and extract variables is stuff what other people already have done:
- https://github.com/Dashlane/css-variables-loader/blob/master/src/index.js#L5-L9
- https://github.com/Coobaha/postcss-variables-loader/blob/master/src/lib/utils.js#L47-L61

I'm not sure why yet, but defining variables in css has my preference. Might be because I'm used to it.

I'd also like to avoid triggering a specific loader when importing in CSS, since the imports are happening very often and results in lots of repetitive code. I could live with it if such a loader is necessary on the javascript-side though, since that's less often happening.

**Comment by EECOLOR** [comment]
> I'd also like to avoid triggering a specific loader when importing in CSS, since the imports are happening very often and results in lots of repetitive code. I could live with it if such a loader is necessary on the javascript-side though, since that's less often happening.

This can be easily avoided:

`theme.css`
```css
@import './cssAndJsVariables.js?asCssVariables'
```

To me it just doesn't make sense to create variables in a string only to later parse them out again.

**Comment by EECOLOR** [comment]
We could also detect a load of a `.js` file [in the `css-loader`](https://github.com/kaliberjs/build/blob/4f0399de50d514ba01b4758945b1f24e6334313b/library/webpack-loaders/css-loader.js#L82), check if it's an object (and reject `null`) and at that point convert to a css variable syntax.

Having a `.js` file seems to be the superior option as it allows us to use configuration information (like absolute external url's).
