### ISSUE TITLE
can't develop in ie11 because of untranspiled modern javascript

### ISSUE THREAD

**Issue by JoostKiens** [kaliberjs/build#79]
Arrow functions, const and other modern javascript is used in at least the following files 
[hot-css-replacement-client.js](https://github.com/kaliberjs/build/blob/644218686874d21e4d16995f7e0065ff719100c3/library/lib/hot-css-replacement-client.js)
[hot-module-replacement-client.js](https://github.com/kaliberjs/build/blob/644218686874d21e4d16995f7e0065ff719100c3/library/lib/hot-module-replacement-client.js)

These are not transpiled before sent to the browser, which means ie11 will throw an error.

**Comment by EECOLOR** [comment]
We could probably add the babel loader here:
https://github.com/kaliberjs/build/blob/644218686874d21e4d16995f7e0065ff719100c3/library/lib/stylesheet.js#L5

**Comment by EECOLOR** [comment]
https://github.com/chalk/ansi-regex/issues/15
