### ISSUE TITLE
Create a documentation site

### ISSUE THREAD

**Issue by EECOLOR** [kaliberjs/build#86]
We can create a documentation site that explains what it does itself. So the documentation could be the example at the same time, showcasing all features.

**Comment by EECOLOR** [comment]
Work in progress: https://github.com/kaliberjs/build/tree/docs

All help is welcome.

**Comment by klaaz0r** [comment]
here is a quick example made with gitbook 

![screen shot 2018-07-25 at 09 01 50](https://user-images.githubusercontent.com/9153800/43184908-896f0638-8fea-11e8-9ac8-2532e3507660.png)

**Comment by EECOLOR** [comment]
Once we have tests (which should share code samples with the documentation) we should re-evaluate the current version of the documentation. If we can make it work with a more common service (like GitBook) I'm all for using something like that.

**Comment by EECOLOR** [comment]
https://kaliberjs.github.io/build/
