### ISSUE TITLE
Create a custom ESLint resolver

### ISSUE THREAD

**Issue by klaasman** [kaliberjs/build#90]
ESLint can warn you when you're trying to import a non-existing (local) modules.
This feature needs a custom resolver:
https://github.com/benmosher/eslint-plugin-import/blob/master/resolvers/README.md

This should also work for absolute imports.

**Comment by EECOLOR** [comment]
Now let's hope they are willing to make vscode configurable: https://github.com/Microsoft/TypeScript/issues/13730
