### ISSUE TITLE
Service worker integration

### ISSUE THREAD

**Issue by klaasman** [kaliberjs/build#97]
For an absolute performance win & even better google pagespeed/audit scores:

https://github.com/goldhand/sw-precache-webpack-plugin

**Comment by EECOLOR** [comment]
It seems the `sw-precache` will be deprecated in favor of https://workboxjs.org/

**Comment by EECOLOR** [comment]
I wonder if we should go down this route. Sites created with `@kaliber/build` tend to have a good page speed score and this stuff will complicate things even more. Creating websites with 'modern' technology is pretty hard compared to what it used to be and I'm hesitant to make it more complicated.

If you compare with the status-quo (of similar businesses) I think we are doing pretty good. My vote would be to close this until we get a signal from our online marketing friends to improve the pagespeed scores.
